routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DiscountCouponController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SettingController;
use App\Models\DiscountCoupon;
use App\Models\ProductVariation;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::middleware(['auth'])->group( function(){
    Route::get('/', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('read.index');
        Route::post('/categories', [CategoryController::class, 'store'])->name('form.store');
        Route::get('/{category}', [CategoryController::class, 'show'])->name('form.show');
        Route::patch('/{category}', [CategoryController::class, 'update'])->name('form.update');
        Route::delete('/categories/{category}', [CategoryController::class], 'destroy')->name('form.delete');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', [ProductController::class, 'index'])->name('read.index');
        Route::post('/products', [ProductController::class, 'store'])->name('form.store');
        Route::get('/{product}', [ProductController::class, 'show'])->name('form.show');
        Route::put('/{product}', [ProductController::class, 'update'])->name('form.update');
        Route::delete('/{product}', [ProductController::class, 'destroy'])->name('form.delete');

        Route::get('/{product}/variations', [ProductController::class, 'productVariation'])->name('show.productVariation');
        Route::post('/{variation}', [ProductController::class, 'storeVariation'])->name('variation.store');
        Route::get('variation/{variation}', [ProductController::class, 'showVariation'])->name('variation.edit');
        Route::patch('variation/{variation}', [ProductController::class, 'variationUpdate'])->name('variation.update');
        Route::delete('/product/{product}', [ProductController::class], 'destroy')->name('variation.delete');

        Route::get('/{product}/images', [ProductController::class, 'showImages'])->name('read.images');
        Route::post('/images/{product}', [ProductController::class, 'storeImage'])->name('store.image');
        Route::get('/images/{image}', [ProductController::class, 'deleteImage'])->name('images.destroy');
    });

    Route::group(['prefix' => 'coupons', 'as' => 'coupons.'], function () {
        Route::get('/', [DiscountCouponController::class, 'index'])->name('read.index');
        Route::post('/coupon', [DiscountCouponController::class, 'store'])->name('form.store');
        Route::get('/{coupon}', [DiscountCouponController::class, 'show'])->name('form.show');
        Route::put('/{coupon}', [DiscountCouponController::class, 'update'])->name('form.update');
        Route::delete('/coupon/{coupon}', [DiscountCouponController::class], 'destroy')->name('form.delete');
    });

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/', [SettingController::class, 'index'])->name('read.index');
        Route::put('/{setting}', [SettingController::class, 'update'])->name('form.update');
    });
});

resources/views/edit-category.blade.php
@extends('layouts.template')

@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Breadcrumbs-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">Edit Category</h5>
                        <!--end::Page Title-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
            </div>
        </div>
        <!--end::Breadcrumbs-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-body">
                        @if(Session::has('message'))
                            <div class="alert alert-info">{{ Session::get('message') }}</div>
                        @endif
                        <form action="{{ route('categories.form.update', $data->id) }}" method="post" enctype="multipart/form-data">
                            <div class="modal-body">
                                @csrf
                                @method('PATCH')
                                <div class="row">
                                    <div class="col-12 form-group">
                                        <label>Name <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Name" name="name" id="name" value="{{ old('name', $data->name) }}" />
                                        @error('name') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-12 form-group">
                                        <label>Status <span class="text-danger">*</span></label>
                                        <select class="form-control" id="kt_select2_2" name="status">
                                            <option value="">Select Status</option>
                                            <option value="1" {{ 1 == old("status", $data->status) ? "selected" : "" }}>Active</option>
                                            <option value="0" {{ 0 == old("status", $data->status) ? "selected" : "" }}>In-Active</option>
                                        </select>
                                        @error('status') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-12 form-group">
                                        <input type="file" class="varitionImage dropzone dropzone-default dropzone-success dz-clickable" name="category_image" id="categoryImages" />
                                    </div>
                                </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                                <input type="submit" value="Save changes" class="btn btn-primary font-weight-bold">
                            </div>
                        </form>
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
    <!--end::Content-->
@endsection
@section('extra-js')
<script>
    $("#categoryImages").dropzone();
</script>
@endsection

resources/views/edit-coupon.blade.php
@extends('layouts.template')

@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Breadcrumbs-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">Edit Coupon</h5>
                        <!--end::Page Title-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
            </div>
        </div>
        <!--end::Breadcrumbs-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-body">
                        @if(Session::has('message'))
                            <div class="alert alert-info">{{ Session::get('message') }}</div>
                        @endif
                        <form action="{{ route('coupons.form.update', $data->id) }}" method="post">
                            <div class="modal-body">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-6 form-group">
                                        <label>Name <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Name" name="name" id="name" value="{{ old('name', $data->name) }}" />
                                        @error('name') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-6 form-group">
                                        <label>Discount Percentage <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Discount Percentage" name="discount_percentage" id="discount_percentage" value="{{ old('discount_percentage', $data->discount_percentage) }}" />
                                        @error('discount_percentage') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 form-group">
                                        <label>Discount Amount <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Discount Amount" name="discount_amount" id="discount_amount" value="{{ old('discount_amount', $data->discount_amount) }}" />
                                        @error('discount_amount') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-6 form-group">
                                        <label>Status <span class="text-danger">*</span></label>
                                        <select class="form-control" id="kt_select2_2" name="status">
                                            <option value="">Select Status</option>
                                            <option value="1" {{ 1 == old("status", $data->status) ? "selected" : "" }}>Active</option>
                                            <option value="0" {{ 0 == old("status", $data->status) ? "selected" : "" }}>In-Active</option>
                                        </select>
                                        @error('status') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                                    <input type="submit" value="Save changes" class="btn btn-primary font-weight-bold">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
    <!--end::Content-->
@endsection

resources/views/edit-variation.blade.php
@extends('layouts.template')

@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Breadcrumbs-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">Edit Variation</h5>
                        <!--end::Page Title-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
            </div>
        </div>
        <!--end::Breadcrumbs-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Card-->
                    <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-body">
                        @if(Session::has('message'))
                            <div class="alert alert-info">{{ Session::get('message') }}</div>
                        @endif
                        <form action="{{ route('products.variation.update', $data->id) }}" method="post" enctype="multipart/form-data">
                            <div class="modal-body">
                                @csrf
                                @method('PATCH')
                                <div class="row">
                                    <div class="col-6 form-group">
                                        <label>Product <span class="text-danger">*</span></label>
                                        <select class="form-control" id="kt_select2_1" name="product_id">
                                            <option value="">Select Product</option>
                                            @foreach ($products as $product)
                                                <option value="{{ $product->id }}" {{ $product->id == old("product_id", $data->product_id) ? "selected" : "" }}>{{ $product->name }}</option>
                                            @endforeach)
                                        </select>
                                        @error('product_id') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-6 form-group">
                                        <label>Variation Type <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Variation Type" name="variation_type" id="variation_type" value="{{ old('variation_type', $data->variation_type) }}" />
                                        @error('variation_type') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 form-group">
                                        <label>Name <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Product Name" name="name" id="name" value="{{ old('name', $data->name) }}" />
                                        @error('name') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-6 form-group">
                                        <label>Price <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Price" name="price" id="price" value="{{ old('price', $data->price) }}" />
                                        @error('price') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 form-group">
                                        <label>Status <span class="text-danger">*</span></label>
                                        <select class="form-control" id="kt_select2_2" name="status">
                                            <option value="">Select Status</option>
                                            <option value="1" {{ 1 == old("status", $data->status) ? "selected" : "" }}>Active</option>
                                            <option value="0" {{ 0 == old("status", $data->status) ? "selected" : "" }}>In-Active</option>
                                        </select>
                                        @error('status') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                    </div>
                                    <div class="col-6 form-group">
                                        <input type="file" class="varitionImage dropzone dropzone-default dropzone-success dz-clickable" name="image_variation" id="varitionImages" />
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a href="{{ URL::previous() }}" class="btn btn-light-primary font-weight-bold">Back to Variations</a>
                                <input type="submit" value="Save changes" class="btn btn-primary font-weight-bold">
                            </div>
                        </form>
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
    <!--end::Content-->
@endsection
@section('extra-js')
<script>
    $("#varitionImages").dropzone();
</script>
@endsection

resources/views/product-images.blade.php
@extends('layouts.template')

@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Breadcrumbs-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">{{ __('product-images.title') }}</h5>
                        <!--end::Page Title-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
            </div>
        </div>
        <!--end::Breadcrumbs-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-header flex-wrap border-0 pt-6 pb-0">
                        <div class="card-title">
                            <h3 class="card-label">{{ __('product-images.heading') }}
                            <span class="d-block text-muted pt-2 font-size-sm">{{ __('product-images.description') }}</span></h3>
                        </div>
                        <div class="card-toolbar">
                            <!--begin::Button-->
                            <a href="#" class="btn btn-primary font-weight-bolder" data-toggle="modal" data-target="#categoryModal">
                            <span class="svg-icon svg-icon-md">
                                <!--begin::Svg Icon | path:/metronic/theme/html/demo1/dist/assets/media/svg/icons/Design/Flatten.svg-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <circle fill="#000000" cx="9" cy="15" r="6" />
                                        <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                    </g>
                                </svg>
                                <!--end::Svg Icon-->
                            </span>{{ __('product-images.new_record') }}</a>
                            <!--end::Button-->
                            <!--begin::Modal to add category-->
                            <div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalSizeSm" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">{{ __('product-images.image') }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <i aria-hidden="true" class="ki ki-close"></i>
                                            </button>
                                        </div>
                                        <form action="{{ route('products.store.image', $product_id) }}" method="post" enctype="multipart/form-data">
                                            <div class="modal-body">
                                                @csrf
                                                <div class="row">
                                                    <div class="col-12 form-group">
                                                        <input type="file" class="varitionImage dropzone dropzone-default dropzone-success dz-clickable" name="product_image" id="productImage" />
                                                        @error('product_image') <span class="form-text text-danger">{{ $message }}</span>@enderror
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">{{ __('product-images.close') }}</button>
                                                <input type="submit" value="{{ __('product-images.save_changes') }}" class="btn btn-primary font-weight-bold">
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!--end::Modal to add category-->
                        </div>
                    </div>
                    <div class="card-body">
                        <!--begin: Search Form-->
                        <div class="mb-7">
                            <div class="row align-items-center">
                                <div class="col-lg-9 col-xl-8">
                                    <div class="row align-items-center">
                                        <div class="col-md-4 my-2 my-md-0">
                                            <div class="input-icon">
                                                <input type="text" class="form-control" placeholder="Search..." id="kt_datatable_search_query" />
                                                <span>
                                                    <i class="flaticon2-search-1 text-muted"></i>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-md-4 my-2 my-md-0">
                                            <div class="d-flex align-items-center">
                                                <label class="mr-3 mb-0 d-none d-md-block">{{ __('product-images.status') }}:</label>
                                                <select class="form-control" id="kt_datatable_search_status">
                                                    <option value="">{{ __('product-images.all') }}</option>
                                                    <option value="1">{{ __('product-images.in_active') }}</option>
                                                    <option value="0">{{ __('product-images.active') }}</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                                    <a href="#" class="btn btn-light-primary px-6 font-weight-bold">{{ __('product-images.search') }}</a>
                                </div>
                            </div>
                        </div>
                        <!--end::Search Form-->
                        @if(Session::has('message'))
                            <div class="alert alert-info">{{ Session::get('message') }}</div>
                        @endif
                        <!--begin: Datatable-->
                        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
                            <thead>
                                <tr>
                                    <th title="Field #1">{{ __('product-images.sr') }}</th>
                                    <th title="Field #1">{{ __('product-images.image') }}</th>
                                    <th title="Field #2">{{ __('product-images.name') }}</th>
                                    <th title="Field #2">{{ __('product-images.size') }}</th>
                                    <th title="Field #2">{{ __('product-images.extension') }}</th>
                                    <th title="Field #3">{{ __('product-images.status') }}</th>
                                    <th title="Field #4">{{ __('product-images.action') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $serial = 1;
                                @endphp
                                @foreach ($images as $image)
                                <tr>
                                    <td>{{ $serial }}</td>
                                    <td><img src="{{ asset('/storage/products/' . $image->name) }}" width="25" height="25"></td>
                                    <td>{{ $image->name }}</td>
                                    <td>{{ $image->size }}</td>
                                    <td>{{ $image->extension }}</td>
                                    <td class="text-right">4</td>
                                    <td>
                                        <span style="overflow: visible; position: relative; width: 125px;">
                                            <a href="{{ route('products.images.destroy', $image->id) }}" class="btn btn-sm btn-clean btn-icon" title="Delete">
                                                <span class="svg-icon svg-icon-md">
                                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                            <rect x="0" y="0" width="24" height="24"></rect>
                                                            <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000" fill-rule="nonzero"></path>
                                                            <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z" fill="#000000" opacity="0.3"></path>
                                                        </g>
                                                    </svg>
                                                </span>
                                            </a>
                                        </span>
                                    </td>
                                </tr>
                                @php
                                    $serial++;
                                @endphp
                                @endforeach
                            </tbody>
                        </table>
                        <!--end: Datatable-->
                    </div>
                </div>
                <!--end::Card-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
    <!--end::Content-->
@endsection
@section('extra-js')
<script>
    $("#productImage").dropzone();
</script>
@endsection